<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-4K45F5E" failures="2" tests="8" name="Test" time="0.059" errors="0" timestamp="2021-06-01T12:50:08 IST">
  <testcase classname="RetryLogicinTestNG.RetryTests" name="test1" time="0.007">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="RetryLogicinTestNG.RetryTests" name="test1" time="0.0">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="RetryLogicinTestNG.RetryTests" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="RetryLogicinTestNG.RetryTests" name="test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogicinTestNG.RetryTests.test1(RetryTests.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="RetryLogicinTestNG.RetryTests" name="test2" time="0.0">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="RetryLogicinTestNG.RetryTests" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="RetryLogicinTestNG.RetryTests" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="RetryLogicinTestNG.RetryTests" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogicinTestNG.RetryTests.test2(RetryTests.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
